import { ReportingSubNav } from '../components/ReportingSubNav';
import { ReportingStatusBadge } from '../components/ReportingStatusBadge';
import { PageHeader } from '@/components/shared/PageHeader';
import { DataTable, type DataTableColumn } from '@/components/shared/DataTable';
import { Card, CardContent } from '@/components/ui';
import { MOCK_HISTORY, type ReportHistoryRow } from '../constants/reporting-data';

export function ReportHistoryPage() {
  const columns: DataTableColumn<ReportHistoryRow>[] = [
    { key: 'report', header: 'Report', render: (r) => <span className="font-medium">{r.report}</span> },
    { key: 'by', header: 'Generated By', render: (r) => r.generatedBy },
    { key: 'at', header: 'Generated Time', render: (r) => r.generatedAt },
    { key: 'params', header: 'Parameters', render: (r) => <code className="text-xs">{r.parameters}</code> },
    { key: 'duration', header: 'Duration', render: (r) => r.duration },
    { key: 'downloads', header: 'Downloads', render: (r) => r.downloads },
    { key: 'status', header: 'Status', render: (r) => <ReportingStatusBadge status={r.status} /> },
  ];

  return (
    <div>
      <PageHeader breadcrumbs={[{ label: 'Reporting', path: '/reports/dashboard' }, { label: 'History' }]} title="Report History" description="Execution history — generator, time, parameters, duration, downloads, and status" />
      <ReportingSubNav />
      <Card><CardContent className="pt-6"><DataTable columns={columns as unknown as DataTableColumn<Record<string, unknown>>[]} rows={MOCK_HISTORY as unknown as Record<string, unknown>[]} rowKey={(r) => String(r.id)} /></CardContent></Card>
    </div>
  );
}
