import type { ServiceKey } from '@/constants/services';

export interface ModuleConfig {
  serviceKey: ServiceKey;
  listPath: string;
  title: string;
  description: string;
  permission?: string;
  displayFields?: string[];
  singleResource?: boolean;
}

export const MODULE_CONFIGS: Record<string, ModuleConfig> = {
  user: {
    serviceKey: 'user',
    listPath: '/users/me',
    title: 'My Profile',
    description: 'Manage your personal information and preferences.',
    singleResource: true,
    displayFields: ['employeeNumber', 'firstName', 'lastName', 'email', 'status', 'rank', 'jobTitle', 'phone'],
  },
  users: {
    serviceKey: 'user',
    listPath: '/users',
    title: 'User Management',
    description: 'Manage platform users, departments, and access.',
    permission: 'personnel:read:profile',
    displayFields: ['employeeNumber', 'firstName', 'lastName', 'email', 'status', 'rank', 'jobTitle'],
  },
  personnel: {
    serviceKey: 'personnel',
    listPath: '/personnel/directory',
    title: 'Personnel',
    description: 'HR records, ranks, assignments, and qualifications.',
    permission: 'personnel:read:profile',
    displayFields: ['serviceNumber', 'firstName', 'lastName', 'rank', 'serviceStatus', 'branch'],
  },
  recruitment: {
    serviceKey: 'recruitment',
    listPath: '/recruitment/vacancies',
    title: 'Recruitment',
    description: 'Job postings, applications, and interviews.',
    permission: 'recruitment:read:applications',
    displayFields: ['title', 'referenceNumber', 'status', 'department', 'closingDate'],
  },
  leave: {
    serviceKey: 'leave',
    listPath: '/leave/requests',
    title: 'Leave Management',
    description: 'Leave requests, balances, and approvals.',
    permission: 'leave:read:requests',
    displayFields: ['requestNumber', 'leaveTypeName', 'status', 'startDate', 'endDate', 'totalDays'],
  },
  welfare: {
    serviceKey: 'welfare',
    listPath: '/welfare/assistance',
    title: 'Welfare',
    description: 'Benefits programs, claims, and dependents.',
    permission: 'welfare:read:claims',
    displayFields: ['claimNumber', 'programName', 'status', 'requestedAmount', 'submittedAt'],
  },
  medical: {
    serviceKey: 'medical',
    listPath: '/medical/appointments',
    title: 'Medical Services',
    description: 'Appointments, records, fitness, and certificates.',
    permission: 'medical:read:appointments',
    displayFields: ['appointmentNumber', 'type', 'status', 'scheduledAt', 'facilityName'],
  },
  training: {
    serviceKey: 'training',
    listPath: '/training/catalog',
    title: 'Training',
    description: 'Courses, sessions, enrollments, and certifications.',
    permission: 'training:read:courses',
    displayFields: ['code', 'title', 'category', 'status', 'duration'],
  },
  performance: {
    serviceKey: 'performance',
    listPath: '/performance/dashboard',
    title: 'Performance Management',
    description: 'Goals, reviews, competencies, feedback, and development plans.',
    permission: 'performance:read:cycles',
    displayFields: ['name', 'status', 'startDate', 'endDate', 'type'],
  },
  asset: {
    serviceKey: 'asset',
    listPath: '/assets/registry',
    title: 'Asset Management',
    description: 'Asset registration, assignment, maintenance, and lifecycle.',
    permission: 'asset:read:assets',
    displayFields: ['assetNumber', 'name', 'category', 'status', 'location'],
  },
  inventory: {
    serviceKey: 'inventory',
    listPath: '/inventory/items',
    title: 'Inventory & Warehouse',
    description: 'Warehouses, stock levels, movements, and requests.',
    permission: 'inventory:read:items',
    displayFields: ['itemCode', 'name', 'category', 'currentStock', 'status'],
  },
  logistics: {
    serviceKey: 'logistics',
    listPath: '/shipments',
    title: 'Logistics',
    description: 'Locations, routes, shipments, and tracking.',
    permission: 'logistics:read:shipments',
    displayFields: ['trackingNumber', 'origin', 'destination', 'status', 'estimatedDelivery'],
  },
  procurement: {
    serviceKey: 'procurement',
    listPath: '/procurement/requisitions',
    title: 'Procurement',
    description: 'Requisitions, suppliers, orders, tenders, and contracts.',
    permission: 'procurement:read:requisitions',
    displayFields: ['requisitionNumber', 'department', 'category', 'status', 'estimatedCost'],
  },
  fleet: {
    serviceKey: 'fleet',
    listPath: '/fleet/dashboard',
    title: 'Logistics & Fleet',
    description: 'Vehicles, drivers, trips, fuel, maintenance, and dispatch.',
    permission: 'fleet:read:vehicles',
    displayFields: ['fleetNumber', 'registrationNumber', 'make', 'model', 'status'],
  },
  dms: {
    serviceKey: 'search',
    listPath: '/dms/dashboard',
    title: 'Documents & Records',
    description: 'Central document store — upload, versioning, signatures, retention, and archive.',
    displayFields: ['documentNumber', 'title', 'category', 'status', 'version'],
  },
  maintenance: {
    serviceKey: 'maintenance',
    listPath: '/work-orders',
    title: 'Maintenance',
    description: 'Work orders, tasks, and maintenance logs.',
    permission: 'maintenance:read:work-orders',
    displayFields: ['referenceNumber', 'title', 'priority', 'status', 'scheduledAt'],
  },
  facilities: {
    serviceKey: 'facilities',
    listPath: '/facilities',
    title: 'Facilities',
    description: 'Facilities, spaces, and bookings.',
    permission: 'facilities:read:facilities',
    displayFields: ['code', 'name', 'type', 'status', 'capacity'],
  },
  finance: {
    serviceKey: 'finance',
    listPath: '/finance/budget-allocation',
    title: 'Finance & Budget',
    description: 'Budget planning, expenditures, invoices, and payments.',
    permission: 'finance:read:budgets',
    displayFields: ['budgetCode', 'department', 'allocatedAmount', 'spentAmount', 'status'],
  },
  visitor: {
    serviceKey: 'visitor',
    listPath: '/visitors',
    title: 'Visitors',
    description: 'Sites, visitors, visits, and check-in.',
    permission: 'visitor:read:visitors',
    displayFields: ['fullName', 'organization', 'idType', 'phone', 'status'],
  },
  workflow: {
    serviceKey: 'workflow',
    listPath: '/instances',
    title: 'Workflow',
    description: 'Definitions, instances, tasks, and approvals.',
    permission: 'workflow:read:instances',
    displayFields: ['referenceNumber', 'definitionName', 'status', 'currentStep', 'startedAt'],
  },
  calendar: {
    serviceKey: 'calendar',
    listPath: '/events',
    title: 'Calendar',
    description: 'Calendars, events, and attendees.',
    permission: 'calendar:read:events',
    displayFields: ['title', 'eventType', 'status', 'startAt', 'endAt', 'location'],
  },
  reporting: {
    serviceKey: 'reporting',
    listPath: '/definitions',
    title: 'Reports',
    description: 'Report definitions, requests, and outputs.',
    permission: 'reporting:read:definitions',
    displayFields: ['code', 'name', 'category', 'format', 'status'],
  },
  analytics: {
    serviceKey: 'analytics',
    listPath: '/dashboards',
    title: 'Analytics',
    description: 'Metrics, dashboards, and queries.',
    permission: 'analytics:read:dashboards',
    displayFields: ['name', 'category', 'status', 'ownerId', 'updatedAt'],
  },
  'business-intelligence': {
    serviceKey: 'business-intelligence',
    listPath: '/datasets',
    title: 'Business Intelligence',
    description: 'Datasets, models, and BI reports.',
    permission: 'bi:read:datasets',
    displayFields: ['name', 'sourceType', 'status', 'rowCount', 'updatedAt'],
  },
  notification: {
    serviceKey: 'notification',
    listPath: '/notifications/inbox',
    title: 'Notifications',
    description: 'Email, SMS, push, and in-app notifications.',
    displayFields: ['title', 'channel', 'status', 'priority', 'createdAt'],
  },
  messaging: {
    serviceKey: 'messaging',
    listPath: '/channels/mine',
    title: 'Messaging',
    description: 'Channels, messages, and delivery.',
    permission: 'messaging:read:channels',
    displayFields: ['name', 'type', 'memberCount', 'lastMessageAt'],
  },
  search: {
    serviceKey: 'search',
    listPath: '/indexes',
    title: 'Search',
    description: 'Indexes, documents, and queries.',
    permission: 'search:read:indexes',
    displayFields: ['name', 'documentCount', 'status', 'lastIndexedAt'],
  },
  'ai-assistant': {
    serviceKey: 'ai-assistant',
    listPath: '/conversations/me',
    title: 'AI Assistant',
    description: 'Agents, conversations, and messages.',
    permission: 'ai:read:conversations',
    displayFields: ['title', 'agentName', 'status', 'messageCount', 'updatedAt'],
  },
  configuration: {
    serviceKey: 'configuration',
    listPath: '/namespaces',
    title: 'System Administration',
    description: 'System administration and configuration.',
    permission: 'configuration:read:namespaces',
    displayFields: ['code', 'name', 'description', 'entryCount'],
  },
  audit: {
    serviceKey: 'audit',
    listPath: '/audit-logs',
    title: 'Audit Logs',
    description: 'Compliance audit logging and security events.',
    permission: 'audit:read:logs',
    displayFields: ['action', 'resourceType', 'userId', 'ipAddress', 'createdAt'],
  },
  settings: {
    serviceKey: 'configuration',
    listPath: '/namespaces',
    title: 'Settings',
    description: 'Platform and user preferences.',
    displayFields: ['code', 'name', 'description'],
  },
};

export function getModuleConfig(moduleKey: string): ModuleConfig | undefined {
  return MODULE_CONFIGS[moduleKey];
}
