import type { NavItem } from '@/types';

export const MAIN_NAVIGATION: NavItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    path: '/dashboard',
    icon: 'FiGrid',
    module: 'dashboard',
    children: [
      { id: 'dashboard-home', label: 'Home Dashboard', path: '/dashboard', icon: 'FiHome', module: 'dashboard' },
      { id: 'dashboard-executive', label: 'Executive Dashboard', path: '/dashboard', icon: 'FiBarChart2', module: 'dashboard' },
      { id: 'dashboard-my', label: 'My Dashboard', path: '/dashboard', icon: 'FiUser', module: 'dashboard' },
    ],
  },
  {
    id: 'recruitment',
    label: 'Recruitment',
    path: '/recruitment/dashboard',
    icon: 'FiUserPlus',
    module: 'recruitment',
    permissions: ['recruitment:read:applications', 'recruitment:read:postings'],
    children: [
      { id: 'recruitment-dashboard', label: 'Dashboard', path: '/recruitment/dashboard', icon: 'FiGrid', module: 'recruitment' },
      { id: 'recruitment-workforce', label: 'Workforce Requests', path: '/recruitment/workforce-requests', icon: 'FiInbox', module: 'recruitment' },
      { id: 'recruitment-requisitions', label: 'Requisitions', path: '/recruitment/requisitions', icon: 'FiFileText', module: 'recruitment' },
      { id: 'recruitment-vacancies', label: 'Vacancies', path: '/recruitment/vacancies', icon: 'FiBriefcase', module: 'recruitment' },
      { id: 'recruitment-applications', label: 'Applications', path: '/recruitment/applications', icon: 'FiUsers', module: 'recruitment' },
      { id: 'recruitment-screening', label: 'Screening', path: '/recruitment/screening', icon: 'FiFilter', module: 'recruitment' },
      { id: 'recruitment-interviews', label: 'Interviews', path: '/recruitment/interviews', icon: 'FiCalendar', module: 'recruitment' },
      { id: 'recruitment-offers', label: 'Offers', path: '/recruitment/offers', icon: 'FiMail', module: 'recruitment' },
      { id: 'recruitment-onboarding', label: 'Onboarding', path: '/recruitment/onboarding', icon: 'FiCheckCircle', module: 'recruitment' },
      { id: 'recruitment-talent', label: 'Talent Pool', path: '/recruitment/talent-pool', icon: 'FiStar', module: 'recruitment' },
      { id: 'recruitment-calendar', label: 'Calendar', path: '/recruitment/calendar', icon: 'FiClock', module: 'recruitment' },
      { id: 'recruitment-reports', label: 'Reports', path: '/recruitment/reports', icon: 'FiBarChart2', module: 'recruitment' },
      { id: 'recruitment-settings', label: 'Settings', path: '/recruitment/settings', icon: 'FiSliders', module: 'recruitment' },
    ],
  },
  {
    id: 'leave',
    label: 'Leave Management',
    path: '/leave/dashboard',
    icon: 'FiCalendar',
    module: 'leave',
    permissions: ['leave:read:requests', 'leave:approve:requests'],
    children: [
      { id: 'leave-dashboard', label: 'Dashboard', path: '/leave/dashboard', icon: 'FiGrid', module: 'leave' },
      { id: 'leave-my', label: 'My Leave', path: '/leave/my-leave', icon: 'FiUser', module: 'leave' },
      { id: 'leave-requests', label: 'Requests', path: '/leave/requests', icon: 'FiFileText', module: 'leave' },
      { id: 'leave-calendar', label: 'Calendar', path: '/leave/calendar', icon: 'FiCalendar', module: 'leave' },
      { id: 'leave-team', label: 'Team Calendar', path: '/leave/team-calendar', icon: 'FiUsers', module: 'leave' },
      { id: 'leave-balances', label: 'Balances', path: '/leave/balances', icon: 'FiPieChart', module: 'leave' },
      { id: 'leave-types', label: 'Leave Types', path: '/leave/types', icon: 'FiLayers', module: 'leave' },
      { id: 'leave-holidays', label: 'Holidays', path: '/leave/holidays', icon: 'FiSun', module: 'leave' },
      { id: 'leave-approvals', label: 'Approvals', path: '/leave/approvals', icon: 'FiCheckCircle', module: 'leave', permissions: ['leave:approve:requests'] },
      { id: 'leave-delegation', label: 'Delegation', path: '/leave/delegation', icon: 'FiShare2', module: 'leave' },
      { id: 'leave-policies', label: 'Policies', path: '/leave/policies', icon: 'FiBook', module: 'leave' },
      { id: 'leave-history', label: 'History', path: '/leave/history', icon: 'FiClock', module: 'leave' },
      { id: 'leave-reports', label: 'Reports', path: '/leave/reports', icon: 'FiBarChart2', module: 'leave' },
      { id: 'leave-settings', label: 'Settings', path: '/leave/settings', icon: 'FiSliders', module: 'leave' },
    ],
  },
  {
    id: 'welfare',
    label: 'Welfare',
    path: '/welfare/dashboard',
    icon: 'FiHeart',
    module: 'welfare',
    permissions: ['welfare:read:claims'],
    children: [
      { id: 'welfare-dashboard', label: 'Dashboard', path: '/welfare/dashboard', icon: 'FiGrid', module: 'welfare' },
      { id: 'welfare-my', label: 'My Welfare', path: '/welfare/my-welfare', icon: 'FiUser', module: 'welfare' },
      { id: 'welfare-programs', label: 'Programs', path: '/welfare/programs', icon: 'FiLayers', module: 'welfare' },
      { id: 'welfare-benefits', label: 'Benefits', path: '/welfare/benefits', icon: 'FiGift', module: 'welfare' },
      { id: 'welfare-assistance', label: 'Assistance', path: '/welfare/assistance', icon: 'FiFileText', module: 'welfare' },
      { id: 'welfare-emergency', label: 'Emergency', path: '/welfare/emergency', icon: 'FiAlertCircle', module: 'welfare' },
      { id: 'welfare-wellness', label: 'Wellness', path: '/welfare/wellness', icon: 'FiActivity', module: 'welfare' },
      { id: 'welfare-events', label: 'Events', path: '/welfare/events', icon: 'FiCalendar', module: 'welfare' },
      { id: 'welfare-applications', label: 'Applications', path: '/welfare/applications', icon: 'FiInbox', module: 'welfare' },
      { id: 'welfare-approvals', label: 'Approvals', path: '/welfare/approvals', icon: 'FiCheckCircle', module: 'welfare', permissions: ['welfare:approve:claims'] },
      { id: 'welfare-documents', label: 'Documents', path: '/welfare/documents', icon: 'FiFile', module: 'welfare' },
      { id: 'welfare-history', label: 'History', path: '/welfare/history', icon: 'FiClock', module: 'welfare' },
      { id: 'welfare-reports', label: 'Reports', path: '/welfare/reports', icon: 'FiBarChart2', module: 'welfare' },
      { id: 'welfare-settings', label: 'Settings', path: '/welfare/settings', icon: 'FiSliders', module: 'welfare' },
    ],
  },
  {
    id: 'medical',
    label: 'Medical',
    path: '/medical/dashboard',
    icon: 'FiActivity',
    module: 'medical',
    permissions: ['medical:read:appointments'],
    children: [
      { id: 'medical-dashboard', label: 'Dashboard', path: '/medical/dashboard', icon: 'FiGrid', module: 'medical' },
      { id: 'medical-my', label: 'My Medical', path: '/medical/my-medical', icon: 'FiUser', module: 'medical' },
      { id: 'medical-profiles', label: 'Profiles', path: '/medical/profiles', icon: 'FiUsers', module: 'medical', permissions: ['medical:manage:records'] },
      { id: 'medical-appointments', label: 'Appointments', path: '/medical/appointments', icon: 'FiCalendar', module: 'medical' },
      { id: 'medical-assessments', label: 'Assessments', path: '/medical/assessments', icon: 'FiClipboard', module: 'medical' },
      { id: 'medical-clearances', label: 'Clearances', path: '/medical/clearances', icon: 'FiCheckCircle', module: 'medical' },
      { id: 'medical-fitness', label: 'Fitness', path: '/medical/fitness', icon: 'FiHeart', module: 'medical' },
      { id: 'medical-vaccinations', label: 'Vaccinations', path: '/medical/vaccinations', icon: 'FiShield', module: 'medical' },
      { id: 'medical-referrals', label: 'Referrals', path: '/medical/referrals', icon: 'FiShare2', module: 'medical' },
      { id: 'medical-calendar', label: 'Calendar', path: '/medical/calendar', icon: 'FiClock', module: 'medical' },
      { id: 'medical-approvals', label: 'Approvals', path: '/medical/approvals', icon: 'FiCheckSquare', module: 'medical', permissions: ['medical:manage:certificates'] },
      { id: 'medical-reports', label: 'Reports', path: '/medical/reports', icon: 'FiBarChart2', module: 'medical' },
      { id: 'medical-history', label: 'History', path: '/medical/history', icon: 'FiList', module: 'medical' },
      { id: 'medical-settings', label: 'Settings', path: '/medical/settings', icon: 'FiSliders', module: 'medical' },
    ],
  },
  {
    id: 'training',
    label: 'Training',
    path: '/training/dashboard',
    icon: 'FiBookOpen',
    module: 'training',
    permissions: ['training:read:courses'],
    children: [
      { id: 'training-dashboard', label: 'Dashboard', path: '/training/dashboard', icon: 'FiGrid', module: 'training' },
      { id: 'training-my-learning', label: 'My Learning', path: '/training/my-learning', icon: 'FiUser', module: 'training' },
      { id: 'training-catalog', label: 'Catalog', path: '/training/catalog', icon: 'FiBook', module: 'training' },
      { id: 'training-programs', label: 'Programs', path: '/training/programs', icon: 'FiLayers', module: 'training' },
      { id: 'training-courses', label: 'Courses', path: '/training/courses', icon: 'FiBookOpen', module: 'training' },
      { id: 'training-paths', label: 'Learning Paths', path: '/training/learning-paths', icon: 'FiMap', module: 'training' },
      { id: 'training-calendar', label: 'Calendar', path: '/training/calendar', icon: 'FiCalendar', module: 'training' },
      { id: 'training-enrollments', label: 'Enrollments', path: '/training/enrollments', icon: 'FiUsers', module: 'training' },
      { id: 'training-certifications', label: 'Certifications', path: '/training/certifications', icon: 'FiAward', module: 'training' },
      { id: 'training-competencies', label: 'Competencies', path: '/training/competencies', icon: 'FiCpu', module: 'training' },
      { id: 'training-approvals', label: 'Approvals', path: '/training/approvals', icon: 'FiCheckCircle', module: 'training', permissions: ['training:manage:enrollments'] },
      { id: 'training-history', label: 'History', path: '/training/history', icon: 'FiClock', module: 'training' },
      { id: 'training-reports', label: 'Reports', path: '/training/reports', icon: 'FiBarChart2', module: 'training' },
      { id: 'training-settings', label: 'Settings', path: '/training/settings', icon: 'FiSliders', module: 'training' },
    ],
  },
  {
    id: 'performance',
    label: 'Performance Management',
    path: '/performance/dashboard',
    icon: 'FiTrendingUp',
    module: 'performance',
    permissions: ['performance:read:cycles'],
    children: [
      { id: 'performance-dashboard', label: 'Dashboard', path: '/performance/dashboard', icon: 'FiGrid', module: 'performance' },
      { id: 'performance-my', label: 'My Performance', path: '/performance/my-performance', icon: 'FiUser', module: 'performance' },
      { id: 'performance-objectives', label: 'Objectives', path: '/performance/objectives', icon: 'FiTarget', module: 'performance' },
      { id: 'performance-reviews', label: 'Reviews', path: '/performance/reviews', icon: 'FiFileText', module: 'performance' },
      { id: 'performance-feedback', label: 'Feedback', path: '/performance/feedback', icon: 'FiMessageSquare', module: 'performance' },
      { id: 'performance-recognition', label: 'Recognition', path: '/performance/recognition', icon: 'FiAward', module: 'performance' },
      { id: 'performance-development', label: 'Development Plans', path: '/performance/development-plans', icon: 'FiBookOpen', module: 'performance' },
      { id: 'performance-cycles', label: 'Review Cycles', path: '/performance/review-cycles', icon: 'FiCalendar', module: 'performance' },
      { id: 'performance-approvals', label: 'Approvals', path: '/performance/approvals', icon: 'FiCheckCircle', module: 'performance' },
      { id: 'performance-reports', label: 'Reports', path: '/performance/reports', icon: 'FiBarChart2', module: 'performance' },
      { id: 'performance-settings', label: 'Settings', path: '/performance/settings', icon: 'FiSliders', module: 'performance' },
    ],
  },
  {
    id: 'personnel',
    label: 'Personnel',
    path: '/personnel/dashboard',
    icon: 'FiUsers',
    module: 'personnel',
    permissions: ['personnel:read:profile', 'personnel:read:records'],
    children: [
      { id: 'personnel-dashboard', label: 'Dashboard', path: '/personnel/dashboard', icon: 'FiGrid', module: 'personnel' },
      { id: 'personnel-directory', label: 'Directory', path: '/personnel/directory', icon: 'FiUsers', module: 'personnel' },
      { id: 'personnel-organization', label: 'Organization', path: '/personnel/organization', icon: 'FiGitBranch', module: 'personnel' },
      { id: 'personnel-departments', label: 'Departments', path: '/personnel/departments', icon: 'FiBriefcase', module: 'personnel' },
      { id: 'personnel-units', label: 'Units', path: '/personnel/units', icon: 'FiLayers', module: 'personnel' },
      { id: 'personnel-positions', label: 'Positions', path: '/personnel/positions', icon: 'FiAward', module: 'personnel' },
      { id: 'personnel-transfers', label: 'Transfers', path: '/personnel/transfers', icon: 'FiShuffle', module: 'personnel' },
      { id: 'personnel-promotions', label: 'Promotions', path: '/personnel/promotions', icon: 'FiTrendingUp', module: 'personnel' },
      { id: 'personnel-qualifications', label: 'Qualifications', path: '/personnel/qualifications', icon: 'FiBook', module: 'personnel' },
      { id: 'personnel-skills', label: 'Skills', path: '/personnel/skills', icon: 'FiCpu', module: 'personnel' },
      { id: 'personnel-documents', label: 'Documents', path: '/personnel/documents', icon: 'FiFile', module: 'personnel' },
      { id: 'personnel-import', label: 'Import', path: '/personnel/import', icon: 'FiUpload', module: 'personnel' },
      { id: 'personnel-export', label: 'Export', path: '/personnel/export', icon: 'FiDownload', module: 'personnel' },
      { id: 'personnel-reports', label: 'Reports', path: '/personnel/reports', icon: 'FiBarChart2', module: 'personnel' },
    ],
  },
  {
    id: 'assets',
    label: 'Asset Management',
    path: '/assets/dashboard',
    icon: 'FiBox',
    module: 'assets',
    permissions: ['asset:read:assets'],
    children: [
      { id: 'assets-dashboard', label: 'Dashboard', path: '/assets/dashboard', icon: 'FiGrid', module: 'assets' },
      { id: 'assets-registry', label: 'Registry', path: '/assets/registry', icon: 'FiList', module: 'assets' },
      { id: 'assets-categories', label: 'Categories', path: '/assets/categories', icon: 'FiLayers', module: 'assets' },
      { id: 'assets-assignment', label: 'Assignment', path: '/assets/assignment', icon: 'FiUserCheck', module: 'assets' },
      { id: 'assets-maintenance', label: 'Maintenance', path: '/assets/maintenance', icon: 'FiTool', module: 'assets' },
      { id: 'assets-inspections', label: 'Inspections', path: '/assets/inspections', icon: 'FiClipboard', module: 'assets' },
      { id: 'assets-reservations', label: 'Reservations', path: '/assets/reservations', icon: 'FiCalendar', module: 'assets' },
      { id: 'assets-audit', label: 'Audit', path: '/assets/audit', icon: 'FiShield', module: 'assets' },
      { id: 'assets-reports', label: 'Reports', path: '/assets/reports', icon: 'FiBarChart2', module: 'assets' },
      { id: 'assets-settings', label: 'Settings', path: '/assets/settings', icon: 'FiSliders', module: 'assets' },
    ],
  },
  {
    id: 'inventory',
    label: 'Inventory & Warehouse',
    path: '/inventory/dashboard',
    icon: 'FiArchive',
    module: 'inventory',
    permissions: ['inventory:read:items'],
    children: [
      { id: 'inventory-dashboard', label: 'Dashboard', path: '/inventory/dashboard', icon: 'FiGrid', module: 'inventory' },
      { id: 'inventory-warehouses', label: 'Warehouses', path: '/inventory/warehouses', icon: 'FiHome', module: 'inventory' },
      { id: 'inventory-items', label: 'Items', path: '/inventory/items', icon: 'FiList', module: 'inventory' },
      { id: 'inventory-stock', label: 'Stock Levels', path: '/inventory/stock-levels', icon: 'FiLayers', module: 'inventory' },
      { id: 'inventory-receipts', label: 'Goods Receipt', path: '/inventory/goods-receipt', icon: 'FiDownload', module: 'inventory' },
      { id: 'inventory-issues', label: 'Goods Issue', path: '/inventory/goods-issue', icon: 'FiUpload', module: 'inventory' },
      { id: 'inventory-requests', label: 'Requests', path: '/inventory/requests', icon: 'FiInbox', module: 'inventory' },
      { id: 'inventory-transfers', label: 'Transfers', path: '/inventory/transfers', icon: 'FiRepeat', module: 'inventory' },
      { id: 'inventory-expiry', label: 'Expiry', path: '/inventory/expiry', icon: 'FiClock', module: 'inventory' },
      { id: 'inventory-reports', label: 'Reports', path: '/inventory/reports', icon: 'FiBarChart2', module: 'inventory' },
      { id: 'inventory-settings', label: 'Settings', path: '/inventory/settings', icon: 'FiSliders', module: 'inventory' },
    ],
  },
  {
    id: 'procurement',
    label: 'Procurement',
    path: '/procurement/dashboard',
    icon: 'FiShoppingCart',
    module: 'procurement',
    permissions: ['procurement:read:requisitions'],
    children: [
      { id: 'procurement-dashboard', label: 'Dashboard', path: '/procurement/dashboard', icon: 'FiGrid', module: 'procurement' },
      { id: 'procurement-requisitions', label: 'Requisitions', path: '/procurement/requisitions', icon: 'FiFileText', module: 'procurement' },
      { id: 'procurement-orders', label: 'Purchase Orders', path: '/procurement/orders', icon: 'FiShoppingBag', module: 'procurement' },
      { id: 'procurement-suppliers', label: 'Suppliers', path: '/procurement/suppliers', icon: 'FiUsers', module: 'procurement' },
      { id: 'procurement-tenders', label: 'Tenders', path: '/procurement/tenders', icon: 'FiAward', module: 'procurement' },
      { id: 'procurement-approvals', label: 'Approvals', path: '/procurement/approvals', icon: 'FiCheckCircle', module: 'procurement' },
      { id: 'procurement-calendar', label: 'Calendar', path: '/procurement/calendar', icon: 'FiCalendar', module: 'procurement' },
      { id: 'procurement-reports', label: 'Reports', path: '/procurement/reports', icon: 'FiBarChart2', module: 'procurement' },
      { id: 'procurement-settings', label: 'Settings', path: '/procurement/settings', icon: 'FiSliders', module: 'procurement' },
    ],
  },
  {
    id: 'fleet',
    label: 'Logistics & Fleet',
    path: '/fleet/dashboard',
    icon: 'FiTruck',
    module: 'fleet',
    permissions: ['fleet:read:vehicles'],
    children: [
      { id: 'fleet-dashboard', label: 'Dashboard', path: '/fleet/dashboard', icon: 'FiGrid', module: 'fleet' },
      { id: 'fleet-registry', label: 'Fleet Registry', path: '/fleet/registry', icon: 'FiList', module: 'fleet' },
      { id: 'fleet-drivers', label: 'Drivers', path: '/fleet/drivers', icon: 'FiUsers', module: 'fleet' },
      { id: 'fleet-assignments', label: 'Assignments', path: '/fleet/assignments', icon: 'FiUserCheck', module: 'fleet' },
      { id: 'fleet-trips', label: 'Trip Requests', path: '/fleet/trip-requests', icon: 'FiMap', module: 'fleet' },
      { id: 'fleet-dispatch', label: 'Dispatch', path: '/fleet/dispatch', icon: 'FiRadio', module: 'fleet' },
      { id: 'fleet-fuel', label: 'Fuel', path: '/fleet/fuel', icon: 'FiDroplet', module: 'fleet' },
      { id: 'fleet-maintenance', label: 'Maintenance', path: '/fleet/maintenance', icon: 'FiTool', module: 'fleet' },
      { id: 'fleet-approvals', label: 'Approvals', path: '/fleet/approvals', icon: 'FiCheckCircle', module: 'fleet' },
      { id: 'fleet-reports', label: 'Reports', path: '/fleet/reports', icon: 'FiBarChart2', module: 'fleet' },
      { id: 'fleet-settings', label: 'Settings', path: '/fleet/settings', icon: 'FiSliders', module: 'fleet' },
    ],
  },
  {
    id: 'operations',
    label: 'Resource Management',
    path: '/logistics',
    icon: 'FiPackage',
    module: 'operations',
    children: [
      { id: 'logistics', label: 'Logistics', path: '/logistics', icon: 'FiTruck', module: 'logistics', permissions: ['logistics:read:shipments'] },
      { id: 'maintenance', label: 'Maintenance', path: '/maintenance', icon: 'FiTool', module: 'maintenance', permissions: ['maintenance:read:work-orders'] },
      { id: 'facilities', label: 'Facilities', path: '/facilities', icon: 'FiHome', module: 'facilities', permissions: ['facilities:read:facilities'] },
    ],
  },
  {
    id: 'finance',
    label: 'Finance & Budget',
    path: '/finance/dashboard',
    icon: 'FiDollarSign',
    module: 'finance',
    permissions: ['finance:read:budgets'],
    children: [
      { id: 'finance-dashboard', label: 'Dashboard', path: '/finance/dashboard', icon: 'FiGrid', module: 'finance' },
      { id: 'finance-budget', label: 'Budget Allocation', path: '/finance/budget-allocation', icon: 'FiPieChart', module: 'finance' },
      { id: 'finance-monitoring', label: 'Budget Monitoring', path: '/finance/budget-monitoring', icon: 'FiActivity', module: 'finance' },
      { id: 'finance-cost-centers', label: 'Cost Centers', path: '/finance/cost-centers', icon: 'FiLayers', module: 'finance' },
      { id: 'finance-expenditures', label: 'Expenditures', path: '/finance/expenditures', icon: 'FiTrendingDown', module: 'finance' },
      { id: 'finance-invoices', label: 'Invoices', path: '/finance/invoices', icon: 'FiFileText', module: 'finance' },
      { id: 'finance-payments', label: 'Payments', path: '/finance/payments', icon: 'FiCreditCard', module: 'finance' },
      { id: 'finance-approvals', label: 'Approvals', path: '/finance/approvals', icon: 'FiCheckCircle', module: 'finance' },
      { id: 'finance-reports', label: 'Reports', path: '/finance/reports', icon: 'FiBarChart2', module: 'finance' },
      { id: 'finance-settings', label: 'Settings', path: '/finance/settings', icon: 'FiSliders', module: 'finance' },
    ],
  },
  {
    id: 'workflow',
    label: 'Workflow & BPM',
    path: '/workflow/dashboard',
    icon: 'FiGitBranch',
    module: 'workflow',
    permissions: ['workflow:read:instances'],
    children: [
      { id: 'workflow-dashboard', label: 'Dashboard', path: '/workflow/dashboard', icon: 'FiGrid', module: 'workflow' },
      { id: 'workflow-templates', label: 'Templates', path: '/workflow/templates', icon: 'FiLayers', module: 'workflow' },
      { id: 'workflow-designer', label: 'Designer', path: '/workflow/designer', icon: 'FiEdit3', module: 'workflow' },
      { id: 'workflow-tasks', label: 'Pending Tasks', path: '/workflow/tasks', icon: 'FiInbox', module: 'workflow' },
      { id: 'workflow-approvals', label: 'My Approvals', path: '/workflow/my-approvals', icon: 'FiCheckCircle', module: 'workflow' },
      { id: 'workflow-running', label: 'Running', path: '/workflow/running', icon: 'FiActivity', module: 'workflow' },
      { id: 'workflow-rules', label: 'Business Rules', path: '/workflow/rules', icon: 'FiCpu', module: 'workflow' },
      { id: 'workflow-sla', label: 'SLA', path: '/workflow/sla', icon: 'FiClock', module: 'workflow' },
      { id: 'workflow-analytics', label: 'Analytics', path: '/workflow/analytics', icon: 'FiBarChart2', module: 'workflow' },
      { id: 'workflow-reports', label: 'Reports', path: '/workflow/reports', icon: 'FiFileText', module: 'workflow' },
      { id: 'workflow-settings', label: 'Settings', path: '/workflow/settings', icon: 'FiSliders', module: 'workflow' },
    ],
  },
  { id: 'visitors', label: 'Visitors', path: '/visitors', icon: 'FiUserCheck', module: 'visitors', permissions: ['visitor:read:visitors'] },
  { id: 'calendar', label: 'Calendar', path: '/calendar', icon: 'FiCalendar', module: 'calendar', permissions: ['calendar:read:events'] },
  {
    id: 'insights',
    label: 'Reporting & Analytics',
    path: '/reports/dashboard',
    icon: 'FiBarChart2',
    module: 'reporting',
    permissions: ['reporting:read:definitions'],
    children: [
      { id: 'reports-dashboard', label: 'Executive Dashboard', path: '/reports/dashboard', icon: 'FiGrid', module: 'reporting' },
      { id: 'reports-operational', label: 'Operational', path: '/reports/operational', icon: 'FiActivity', module: 'reporting' },
      { id: 'reports-kpis', label: 'KPI Management', path: '/reports/kpis', icon: 'FiActivity', module: 'reporting' },
      { id: 'reports-library', label: 'Report Library', path: '/reports/library', icon: 'FiFileText', module: 'reporting' },
      { id: 'reports-builder', label: 'Report Builder', path: '/reports/builder', icon: 'FiEdit3', module: 'reporting' },
      { id: 'reports-analytics', label: 'Analytics', path: '/reports/analytics', icon: 'FiPieChart', module: 'reporting' },
      { id: 'reports-forecasting', label: 'Forecasting', path: '/reports/forecasting', icon: 'FiTrendingUp', module: 'reporting' },
      { id: 'reports-exports', label: 'Data Exports', path: '/reports/exports', icon: 'FiDownload', module: 'reporting' },
      { id: 'reports-integrations', label: 'BI Integrations', path: '/reports/integrations', icon: 'FiLayers', module: 'reporting' },
      { id: 'reports-settings', label: 'Settings', path: '/reports/settings', icon: 'FiSliders', module: 'reporting' },
    ],
  },
  {
    id: 'communication',
    label: 'Notification & Communication',
    path: '/notifications/dashboard',
    icon: 'FiMessageCircle',
    module: 'notification',
    permissions: ['notification:read:notifications'],
    children: [
      { id: 'notification-dashboard', label: 'Dashboard', path: '/notifications/dashboard', icon: 'FiGrid', module: 'notification' },
      { id: 'notification-center', label: 'Notification Center', path: '/notifications/center', icon: 'FiBell', module: 'notification', badge: 3 },
      { id: 'notification-my', label: 'My Notifications', path: '/notifications/my', icon: 'FiInbox', module: 'notification' },
      { id: 'notification-announcements', label: 'Announcements', path: '/notifications/announcements', icon: 'FiVolume2', module: 'notification' },
      { id: 'notification-broadcast', label: 'Broadcast', path: '/notifications/broadcast', icon: 'FiSend', module: 'notification' },
      { id: 'notification-templates', label: 'Templates', path: '/notifications/templates', icon: 'FiLayers', module: 'notification' },
      { id: 'notification-delivery', label: 'Delivery', path: '/notifications/delivery', icon: 'FiTruck', module: 'notification' },
      { id: 'notification-reports', label: 'Reports', path: '/notifications/reports', icon: 'FiFileText', module: 'notification' },
      { id: 'notification-settings', label: 'Settings', path: '/notifications/settings', icon: 'FiSliders', module: 'notification' },
      { id: 'messaging', label: 'Messages', path: '/messaging', icon: 'FiMessageSquare', module: 'messaging', permissions: ['messaging:read:channels'] },
    ],
  },
  { id: 'search', label: 'Search', path: '/search', icon: 'FiSearch', module: 'search', permissions: ['search:read:indexes'] },
  { id: 'ai-assistant', label: 'AI Assistant', path: '/ai-assistant', icon: 'FiCpu', module: 'ai-assistant', permissions: ['ai:read:conversations'] },
  {
    id: 'authentication',
    label: 'Authentication',
    path: '/auth/security',
    icon: 'FiLock',
    module: 'authentication',
    children: [
      { id: 'auth-security', label: 'Security Settings', path: '/auth/security', icon: 'FiShield', module: 'authentication' },
      { id: 'auth-sessions', label: 'Sessions', path: '/auth/sessions', icon: 'FiMonitor', module: 'authentication' },
      { id: 'auth-login-history', label: 'Login History', path: '/auth/login-history', icon: 'FiClock', module: 'authentication' },
      { id: 'auth-devices', label: 'Device Management', path: '/auth/devices', icon: 'FiSmartphone', module: 'authentication' },
      { id: 'auth-change-password', label: 'Change Password', path: '/auth/change-password', icon: 'FiKey', module: 'authentication' },
    ],
  },
  {
    id: 'dms',
    label: 'Documents & Records',
    path: '/dms/dashboard',
    icon: 'FiFolder',
    module: 'dms',
    children: [
      { id: 'dms-dashboard', label: 'Dashboard', path: '/dms/dashboard', icon: 'FiGrid', module: 'dms' },
      { id: 'dms-library', label: 'Library', path: '/dms/library', icon: 'FiFileText', module: 'dms' },
      { id: 'dms-my', label: 'My Documents', path: '/dms/my-documents', icon: 'FiUser', module: 'dms' },
      { id: 'dms-shared', label: 'Shared', path: '/dms/shared', icon: 'FiShare2', module: 'dms' },
      { id: 'dms-folders', label: 'Folders', path: '/dms/folders', icon: 'FiFolder', module: 'dms' },
      { id: 'dms-upload', label: 'Upload', path: '/dms/upload', icon: 'FiUpload', module: 'dms' },
      { id: 'dms-approvals', label: 'Approvals', path: '/dms/approvals', icon: 'FiCheckCircle', module: 'dms' },
      { id: 'dms-signatures', label: 'Signatures', path: '/dms/signatures', icon: 'FiEdit3', module: 'dms' },
      { id: 'dms-retention', label: 'Retention', path: '/dms/retention', icon: 'FiClock', module: 'dms' },
      { id: 'dms-search', label: 'Search', path: '/dms/search', icon: 'FiSearch', module: 'dms' },
      { id: 'dms-reports', label: 'Reports', path: '/dms/reports', icon: 'FiBarChart2', module: 'dms' },
      { id: 'dms-settings', label: 'Settings', path: '/dms/settings', icon: 'FiSliders', module: 'dms' },
    ],
  },
  {
    id: 'authorization',
    label: 'Authorization',
    path: '/administration/authorization',
    icon: 'FiShield',
    module: 'authorization',
    roles: ['SUPER_ADMIN', 'ADMIN'],
    children: [
      { id: 'authz-dashboard', label: 'Dashboard', path: '/administration/authorization', icon: 'FiGrid', module: 'authorization', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'roles', label: 'Roles', path: '/administration/roles', icon: 'FiShield', module: 'roles', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'permissions', label: 'Permissions', path: '/administration/permissions', icon: 'FiKey', module: 'permissions', roles: ['SUPER_ADMIN'] },
      { id: 'permission-groups', label: 'Permission Groups', path: '/administration/permission-groups', icon: 'FiLayers', module: 'authorization', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'role-hierarchy', label: 'Role Hierarchy', path: '/administration/role-hierarchy', icon: 'FiGitBranch', module: 'authorization', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'assignments', label: 'User Assignments', path: '/administration/assignments', icon: 'FiUsers', module: 'authorization', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'resource-perms', label: 'Resource Permissions', path: '/administration/resource-permissions', icon: 'FiBox', module: 'authorization', roles: ['SUPER_ADMIN'] },
      { id: 'menu-perms', label: 'Menu Permissions', path: '/administration/menu-permissions', icon: 'FiMenu', module: 'authorization', roles: ['SUPER_ADMIN'] },
      { id: 'action-perms', label: 'Action Permissions', path: '/administration/action-permissions', icon: 'FiZap', module: 'authorization', roles: ['SUPER_ADMIN'] },
      { id: 'approval-levels', label: 'Approval Levels', path: '/administration/approval-levels', icon: 'FiCheckCircle', module: 'authorization', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'delegated-access', label: 'Delegated Access', path: '/administration/delegated-access', icon: 'FiShare2', module: 'authorization', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'access-policies', label: 'Access Policies', path: '/administration/access-policies', icon: 'FiFileText', module: 'authorization', roles: ['SUPER_ADMIN'] },
      { id: 'access-requests', label: 'Access Requests', path: '/administration/access-requests', icon: 'FiInbox', module: 'authorization', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'temporary-access', label: 'Temporary Access', path: '/administration/temporary-access', icon: 'FiClock', module: 'authorization', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'permission-audit', label: 'Permission Audit', path: '/administration/permission-audit', icon: 'FiClipboard', module: 'authorization', roles: ['SUPER_ADMIN'] },
      { id: 'authz-settings', label: 'Auth Settings', path: '/administration/authorization-settings', icon: 'FiSliders', module: 'authorization', roles: ['SUPER_ADMIN'] },
    ],
  },
  {
    id: 'users',
    label: 'User Management',
    path: '/users/dashboard',
    icon: 'FiUser',
    module: 'users',
    roles: ['SUPER_ADMIN', 'ADMIN'],
    permissions: ['personnel:read:profile'],
    children: [
      { id: 'users-dashboard', label: 'Dashboard', path: '/users/dashboard', icon: 'FiGrid', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'users-list', label: 'All Users', path: '/users/list', icon: 'FiUsers', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'users-departments', label: 'Departments', path: '/users/departments', icon: 'FiBriefcase', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'users-positions', label: 'Positions', path: '/users/positions', icon: 'FiAward', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'users-organization', label: 'Organization', path: '/users/organization', icon: 'FiGitBranch', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'users-status', label: 'User Status', path: '/users/status', icon: 'FiActivity', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'users-documents', label: 'Documents', path: '/users/documents', icon: 'FiFile', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'users-import', label: 'Import', path: '/users/import', icon: 'FiUpload', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'users-export', label: 'Export', path: '/users/export', icon: 'FiDownload', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'users-history', label: 'History', path: '/users/history', icon: 'FiClock', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'users-settings', label: 'Settings', path: '/users/settings', icon: 'FiSliders', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
    ],
  },
  {
    id: 'admin',
    label: 'Administration',
    path: '/administration',
    icon: 'FiSettings',
    module: 'admin',
    roles: ['SUPER_ADMIN', 'ADMIN'],
    children: [
      { id: 'audit', label: 'Audit Logs', path: '/audit-logs', icon: 'FiClipboard', module: 'audit', permissions: ['audit:read:logs'] },
      { id: 'settings', label: 'Settings', path: '/settings', icon: 'FiSliders', module: 'settings' },
      { id: 'administration', label: 'System Admin', path: '/administration', icon: 'FiServer', module: 'administration', roles: ['SUPER_ADMIN'] },
    ],
  },
];

export const QUICK_ACTIONS = [
  { label: 'New Leave Request', path: '/leave/new', icon: 'FiCalendar' },
  { label: 'Submit Requisition', path: '/procurement/requisitions/new', icon: 'FiShoppingCart' },
  { label: 'View Reports', path: '/reports', icon: 'FiFileText' },
];
