import type { NavItem } from '@/types';

export const MAIN_NAVIGATION: NavItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    path: '/dashboard',
    icon: 'FiGrid',
    module: 'dashboard',
    children: [
      { id: 'dashboard-home', label: 'Home Dashboard', path: '/dashboard', icon: 'FiHome', module: 'dashboard' },
      { id: 'dashboard-executive', label: 'Executive Dashboard', path: '/dashboard', icon: 'FiBarChart2', module: 'dashboard' },
      { id: 'dashboard-my', label: 'My Dashboard', path: '/dashboard', icon: 'FiUser', module: 'dashboard' },
    ],
  },
  {
    id: 'recruitment',
    label: 'Recruitment',
    path: '/recruitment/dashboard',
    icon: 'FiUserPlus',
    module: 'recruitment',
    permissions: ['recruitment:read:applications', 'recruitment:read:postings'],
    children: [
      { id: 'recruitment-dashboard', label: 'Dashboard', path: '/recruitment/dashboard', icon: 'FiGrid', module: 'recruitment' },
      { id: 'recruitment-workforce', label: 'Workforce Requests', path: '/recruitment/workforce-requests', icon: 'FiInbox', module: 'recruitment' },
      { id: 'recruitment-requisitions', label: 'Requisitions', path: '/recruitment/requisitions', icon: 'FiFileText', module: 'recruitment' },
      { id: 'recruitment-vacancies', label: 'Vacancies', path: '/recruitment/vacancies', icon: 'FiBriefcase', module: 'recruitment' },
      { id: 'recruitment-applications', label: 'Applications', path: '/recruitment/applications', icon: 'FiUsers', module: 'recruitment' },
      { id: 'recruitment-screening', label: 'Screening', path: '/recruitment/screening', icon: 'FiFilter', module: 'recruitment' },
      { id: 'recruitment-interviews', label: 'Interviews', path: '/recruitment/interviews', icon: 'FiCalendar', module: 'recruitment' },
      { id: 'recruitment-offers', label: 'Offers', path: '/recruitment/offers', icon: 'FiMail', module: 'recruitment' },
      { id: 'recruitment-onboarding', label: 'Onboarding', path: '/recruitment/onboarding', icon: 'FiCheckCircle', module: 'recruitment' },
      { id: 'recruitment-talent', label: 'Talent Pool', path: '/recruitment/talent-pool', icon: 'FiStar', module: 'recruitment' },
      { id: 'recruitment-calendar', label: 'Calendar', path: '/recruitment/calendar', icon: 'FiClock', module: 'recruitment' },
      { id: 'recruitment-reports', label: 'Reports', path: '/recruitment/reports', icon: 'FiBarChart2', module: 'recruitment' },
      { id: 'recruitment-settings', label: 'Settings', path: '/recruitment/settings', icon: 'FiSliders', module: 'recruitment' },
    ],
  },
  {
    id: 'leave',
    label: 'Leave Management',
    path: '/leave/dashboard',
    icon: 'FiCalendar',
    module: 'leave',
    permissions: ['leave:read:requests', 'leave:approve:requests'],
    children: [
      { id: 'leave-dashboard', label: 'Dashboard', path: '/leave/dashboard', icon: 'FiGrid', module: 'leave' },
      { id: 'leave-my', label: 'My Leave', path: '/leave/my-leave', icon: 'FiUser', module: 'leave' },
      { id: 'leave-requests', label: 'Requests', path: '/leave/requests', icon: 'FiFileText', module: 'leave' },
      { id: 'leave-calendar', label: 'Calendar', path: '/leave/calendar', icon: 'FiCalendar', module: 'leave' },
      { id: 'leave-team', label: 'Team Calendar', path: '/leave/team-calendar', icon: 'FiUsers', module: 'leave' },
      { id: 'leave-balances', label: 'Balances', path: '/leave/balances', icon: 'FiPieChart', module: 'leave' },
      { id: 'leave-types', label: 'Leave Types', path: '/leave/types', icon: 'FiLayers', module: 'leave' },
      { id: 'leave-holidays', label: 'Holidays', path: '/leave/holidays', icon: 'FiSun', module: 'leave' },
      { id: 'leave-approvals', label: 'Approvals', path: '/leave/approvals', icon: 'FiCheckCircle', module: 'leave', permissions: ['leave:approve:requests'] },
      { id: 'leave-delegation', label: 'Delegation', path: '/leave/delegation', icon: 'FiShare2', module: 'leave' },
      { id: 'leave-policies', label: 'Policies', path: '/leave/policies', icon: 'FiBook', module: 'leave' },
      { id: 'leave-history', label: 'History', path: '/leave/history', icon: 'FiClock', module: 'leave' },
      { id: 'leave-reports', label: 'Reports', path: '/leave/reports', icon: 'FiBarChart2', module: 'leave' },
      { id: 'leave-settings', label: 'Settings', path: '/leave/settings', icon: 'FiSliders', module: 'leave' },
    ],
  },
  {
    id: 'hr',
    label: 'Human Resources',
    path: '/personnel/dashboard',
    icon: 'FiUsers',
    module: 'hr',
    children: [
      { id: 'welfare', label: 'Welfare', path: '/welfare', icon: 'FiHeart', module: 'welfare', permissions: ['welfare:read:claims'] },
      { id: 'medical', label: 'Medical', path: '/medical', icon: 'FiActivity', module: 'medical', permissions: ['medical:read:appointments'] },
      { id: 'training', label: 'Training', path: '/training', icon: 'FiBookOpen', module: 'training', permissions: ['training:read:courses'] },
      { id: 'performance', label: 'Performance', path: '/performance', icon: 'FiTrendingUp', module: 'performance', permissions: ['performance:read:cycles'] },
    ],
  },
  {
    id: 'personnel',
    label: 'Personnel',
    path: '/personnel/dashboard',
    icon: 'FiUsers',
    module: 'personnel',
    permissions: ['personnel:read:profile', 'personnel:read:records'],
    children: [
      { id: 'personnel-dashboard', label: 'Dashboard', path: '/personnel/dashboard', icon: 'FiGrid', module: 'personnel' },
      { id: 'personnel-directory', label: 'Directory', path: '/personnel/directory', icon: 'FiUsers', module: 'personnel' },
      { id: 'personnel-organization', label: 'Organization', path: '/personnel/organization', icon: 'FiGitBranch', module: 'personnel' },
      { id: 'personnel-departments', label: 'Departments', path: '/personnel/departments', icon: 'FiBriefcase', module: 'personnel' },
      { id: 'personnel-units', label: 'Units', path: '/personnel/units', icon: 'FiLayers', module: 'personnel' },
      { id: 'personnel-positions', label: 'Positions', path: '/personnel/positions', icon: 'FiAward', module: 'personnel' },
      { id: 'personnel-transfers', label: 'Transfers', path: '/personnel/transfers', icon: 'FiShuffle', module: 'personnel' },
      { id: 'personnel-promotions', label: 'Promotions', path: '/personnel/promotions', icon: 'FiTrendingUp', module: 'personnel' },
      { id: 'personnel-qualifications', label: 'Qualifications', path: '/personnel/qualifications', icon: 'FiBook', module: 'personnel' },
      { id: 'personnel-skills', label: 'Skills', path: '/personnel/skills', icon: 'FiCpu', module: 'personnel' },
      { id: 'personnel-documents', label: 'Documents', path: '/personnel/documents', icon: 'FiFile', module: 'personnel' },
      { id: 'personnel-import', label: 'Import', path: '/personnel/import', icon: 'FiUpload', module: 'personnel' },
      { id: 'personnel-export', label: 'Export', path: '/personnel/export', icon: 'FiDownload', module: 'personnel' },
      { id: 'personnel-reports', label: 'Reports', path: '/personnel/reports', icon: 'FiBarChart2', module: 'personnel' },
    ],
  },
  {
    id: 'operations',
    label: 'Resource Management',
    path: '/assets',
    icon: 'FiPackage',
    module: 'operations',
    children: [
      { id: 'assets', label: 'Assets', path: '/assets', icon: 'FiBox', module: 'assets', permissions: ['asset:read:assets'] },
      { id: 'inventory', label: 'Inventory', path: '/inventory', icon: 'FiArchive', module: 'inventory', permissions: ['inventory:read:items'] },
      { id: 'logistics', label: 'Logistics', path: '/logistics', icon: 'FiTruck', module: 'logistics', permissions: ['logistics:read:shipments'] },
      { id: 'procurement', label: 'Procurement', path: '/procurement', icon: 'FiShoppingCart', module: 'procurement', permissions: ['procurement:read:requisitions'] },
      { id: 'fleet', label: 'Fleet', path: '/fleet', icon: 'FiNavigation', module: 'fleet', permissions: ['fleet:read:vehicles'] },
      { id: 'maintenance', label: 'Maintenance', path: '/maintenance', icon: 'FiTool', module: 'maintenance', permissions: ['maintenance:read:work-orders'] },
      { id: 'facilities', label: 'Facilities', path: '/facilities', icon: 'FiHome', module: 'facilities', permissions: ['facilities:read:facilities'] },
    ],
  },
  { id: 'finance', label: 'Finance', path: '/finance', icon: 'FiDollarSign', module: 'finance', permissions: ['finance:read:budgets'] },
  { id: 'visitors', label: 'Visitors', path: '/visitors', icon: 'FiUserCheck', module: 'visitors', permissions: ['visitor:read:visitors'] },
  { id: 'workflow', label: 'Workflow', path: '/workflow', icon: 'FiGitBranch', module: 'workflow', permissions: ['workflow:read:instances'] },
  { id: 'calendar', label: 'Calendar', path: '/calendar', icon: 'FiCalendar', module: 'calendar', permissions: ['calendar:read:events'] },
  {
    id: 'insights',
    label: 'Intelligence',
    path: '/reports',
    icon: 'FiBarChart2',
    module: 'insights',
    children: [
      { id: 'reports', label: 'Reports', path: '/reports', icon: 'FiFileText', module: 'reports', permissions: ['reporting:read:definitions'] },
      { id: 'analytics', label: 'Analytics', path: '/analytics', icon: 'FiPieChart', module: 'analytics', permissions: ['analytics:read:dashboards'] },
      { id: 'bi', label: 'Business Intelligence', path: '/business-intelligence', icon: 'FiLayers', module: 'bi', permissions: ['bi:read:datasets'] },
    ],
  },
  {
    id: 'communication',
    label: 'Communication',
    path: '/notifications',
    icon: 'FiMessageCircle',
    module: 'communication',
    children: [
      { id: 'notifications', label: 'Notifications', path: '/notifications', icon: 'FiBell', module: 'notifications', permissions: ['notification:read:notifications'], badge: 3 },
      { id: 'messaging', label: 'Messages', path: '/messaging', icon: 'FiMessageSquare', module: 'messaging', permissions: ['messaging:read:channels'] },
      { id: 'announcements', label: 'Announcements', path: '/notifications', icon: 'FiVolume2', module: 'announcements' },
    ],
  },
  { id: 'search', label: 'Search', path: '/search', icon: 'FiSearch', module: 'search', permissions: ['search:read:indexes'] },
  { id: 'ai-assistant', label: 'AI Assistant', path: '/ai-assistant', icon: 'FiCpu', module: 'ai-assistant', permissions: ['ai:read:conversations'] },
  {
    id: 'authentication',
    label: 'Authentication',
    path: '/auth/security',
    icon: 'FiLock',
    module: 'authentication',
    children: [
      { id: 'auth-security', label: 'Security Settings', path: '/auth/security', icon: 'FiShield', module: 'authentication' },
      { id: 'auth-sessions', label: 'Sessions', path: '/auth/sessions', icon: 'FiMonitor', module: 'authentication' },
      { id: 'auth-login-history', label: 'Login History', path: '/auth/login-history', icon: 'FiClock', module: 'authentication' },
      { id: 'auth-devices', label: 'Device Management', path: '/auth/devices', icon: 'FiSmartphone', module: 'authentication' },
      { id: 'auth-change-password', label: 'Change Password', path: '/auth/change-password', icon: 'FiKey', module: 'authentication' },
    ],
  },
  {
    id: 'authorization',
    label: 'Authorization',
    path: '/administration/authorization',
    icon: 'FiShield',
    module: 'authorization',
    roles: ['SUPER_ADMIN', 'ADMIN'],
    children: [
      { id: 'authz-dashboard', label: 'Dashboard', path: '/administration/authorization', icon: 'FiGrid', module: 'authorization', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'roles', label: 'Roles', path: '/administration/roles', icon: 'FiShield', module: 'roles', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'permissions', label: 'Permissions', path: '/administration/permissions', icon: 'FiKey', module: 'permissions', roles: ['SUPER_ADMIN'] },
      { id: 'permission-groups', label: 'Permission Groups', path: '/administration/permission-groups', icon: 'FiLayers', module: 'authorization', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'role-hierarchy', label: 'Role Hierarchy', path: '/administration/role-hierarchy', icon: 'FiGitBranch', module: 'authorization', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'assignments', label: 'User Assignments', path: '/administration/assignments', icon: 'FiUsers', module: 'authorization', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'resource-perms', label: 'Resource Permissions', path: '/administration/resource-permissions', icon: 'FiBox', module: 'authorization', roles: ['SUPER_ADMIN'] },
      { id: 'menu-perms', label: 'Menu Permissions', path: '/administration/menu-permissions', icon: 'FiMenu', module: 'authorization', roles: ['SUPER_ADMIN'] },
      { id: 'action-perms', label: 'Action Permissions', path: '/administration/action-permissions', icon: 'FiZap', module: 'authorization', roles: ['SUPER_ADMIN'] },
      { id: 'approval-levels', label: 'Approval Levels', path: '/administration/approval-levels', icon: 'FiCheckCircle', module: 'authorization', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'delegated-access', label: 'Delegated Access', path: '/administration/delegated-access', icon: 'FiShare2', module: 'authorization', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'access-policies', label: 'Access Policies', path: '/administration/access-policies', icon: 'FiFileText', module: 'authorization', roles: ['SUPER_ADMIN'] },
      { id: 'access-requests', label: 'Access Requests', path: '/administration/access-requests', icon: 'FiInbox', module: 'authorization', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'temporary-access', label: 'Temporary Access', path: '/administration/temporary-access', icon: 'FiClock', module: 'authorization', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'permission-audit', label: 'Permission Audit', path: '/administration/permission-audit', icon: 'FiClipboard', module: 'authorization', roles: ['SUPER_ADMIN'] },
      { id: 'authz-settings', label: 'Auth Settings', path: '/administration/authorization-settings', icon: 'FiSliders', module: 'authorization', roles: ['SUPER_ADMIN'] },
    ],
  },
  {
    id: 'users',
    label: 'User Management',
    path: '/users/dashboard',
    icon: 'FiUser',
    module: 'users',
    roles: ['SUPER_ADMIN', 'ADMIN'],
    permissions: ['personnel:read:profile'],
    children: [
      { id: 'users-dashboard', label: 'Dashboard', path: '/users/dashboard', icon: 'FiGrid', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'users-list', label: 'All Users', path: '/users/list', icon: 'FiUsers', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'users-departments', label: 'Departments', path: '/users/departments', icon: 'FiBriefcase', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'users-positions', label: 'Positions', path: '/users/positions', icon: 'FiAward', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'users-organization', label: 'Organization', path: '/users/organization', icon: 'FiGitBranch', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'users-status', label: 'User Status', path: '/users/status', icon: 'FiActivity', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'users-documents', label: 'Documents', path: '/users/documents', icon: 'FiFile', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'users-import', label: 'Import', path: '/users/import', icon: 'FiUpload', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'users-export', label: 'Export', path: '/users/export', icon: 'FiDownload', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'users-history', label: 'History', path: '/users/history', icon: 'FiClock', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'users-settings', label: 'Settings', path: '/users/settings', icon: 'FiSliders', module: 'users', roles: ['SUPER_ADMIN', 'ADMIN'] },
    ],
  },
  {
    id: 'admin',
    label: 'Administration',
    path: '/administration',
    icon: 'FiSettings',
    module: 'admin',
    roles: ['SUPER_ADMIN', 'ADMIN'],
    children: [
      { id: 'audit', label: 'Audit Logs', path: '/audit-logs', icon: 'FiClipboard', module: 'audit', permissions: ['audit:read:logs'] },
      { id: 'settings', label: 'Settings', path: '/settings', icon: 'FiSliders', module: 'settings' },
      { id: 'administration', label: 'System Admin', path: '/administration', icon: 'FiServer', module: 'administration', roles: ['SUPER_ADMIN'] },
    ],
  },
];

export const QUICK_ACTIONS = [
  { label: 'New Leave Request', path: '/leave/new', icon: 'FiCalendar' },
  { label: 'Submit Requisition', path: '/procurement/requisitions/new', icon: 'FiShoppingCart' },
  { label: 'View Reports', path: '/reports', icon: 'FiFileText' },
];
