import type { NavItem } from '@/types';

export const MAIN_NAVIGATION: NavItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    path: '/dashboard',
    icon: 'FiGrid',
    module: 'dashboard',
    children: [
      { id: 'dashboard-home', label: 'Home Dashboard', path: '/dashboard', icon: 'FiHome', module: 'dashboard' },
      { id: 'dashboard-executive', label: 'Executive Dashboard', path: '/dashboard', icon: 'FiBarChart2', module: 'dashboard' },
      { id: 'dashboard-my', label: 'My Dashboard', path: '/dashboard', icon: 'FiUser', module: 'dashboard' },
    ],
  },
  {
    id: 'hr',
    label: 'Human Resources',
    path: '/personnel',
    icon: 'FiUsers',
    module: 'hr',
    children: [
      { id: 'personnel', label: 'Personnel', path: '/personnel', icon: 'FiUsers', module: 'personnel', permissions: ['personnel:read:records'] },
      { id: 'recruitment', label: 'Recruitment', path: '/recruitment', icon: 'FiUserPlus', module: 'recruitment', permissions: ['recruitment:read:postings'] },
      { id: 'leave', label: 'Leave', path: '/leave', icon: 'FiCalendar', module: 'leave', permissions: ['leave:read:requests'] },
      { id: 'welfare', label: 'Welfare', path: '/welfare', icon: 'FiHeart', module: 'welfare', permissions: ['welfare:read:claims'] },
      { id: 'medical', label: 'Medical', path: '/medical', icon: 'FiActivity', module: 'medical', permissions: ['medical:read:appointments'] },
      { id: 'training', label: 'Training', path: '/training', icon: 'FiBookOpen', module: 'training', permissions: ['training:read:courses'] },
      { id: 'performance', label: 'Performance', path: '/performance', icon: 'FiTrendingUp', module: 'performance', permissions: ['performance:read:cycles'] },
    ],
  },
  {
    id: 'operations',
    label: 'Resource Management',
    path: '/assets',
    icon: 'FiPackage',
    module: 'operations',
    children: [
      { id: 'assets', label: 'Assets', path: '/assets', icon: 'FiBox', module: 'assets', permissions: ['asset:read:assets'] },
      { id: 'inventory', label: 'Inventory', path: '/inventory', icon: 'FiArchive', module: 'inventory', permissions: ['inventory:read:items'] },
      { id: 'logistics', label: 'Logistics', path: '/logistics', icon: 'FiTruck', module: 'logistics', permissions: ['logistics:read:shipments'] },
      { id: 'procurement', label: 'Procurement', path: '/procurement', icon: 'FiShoppingCart', module: 'procurement', permissions: ['procurement:read:requisitions'] },
      { id: 'fleet', label: 'Fleet', path: '/fleet', icon: 'FiNavigation', module: 'fleet', permissions: ['fleet:read:vehicles'] },
      { id: 'maintenance', label: 'Maintenance', path: '/maintenance', icon: 'FiTool', module: 'maintenance', permissions: ['maintenance:read:work-orders'] },
      { id: 'facilities', label: 'Facilities', path: '/facilities', icon: 'FiHome', module: 'facilities', permissions: ['facilities:read:facilities'] },
    ],
  },
  { id: 'finance', label: 'Finance', path: '/finance', icon: 'FiDollarSign', module: 'finance', permissions: ['finance:read:budgets'] },
  { id: 'visitors', label: 'Visitors', path: '/visitors', icon: 'FiUserCheck', module: 'visitors', permissions: ['visitor:read:visitors'] },
  { id: 'workflow', label: 'Workflow', path: '/workflow', icon: 'FiGitBranch', module: 'workflow', permissions: ['workflow:read:instances'] },
  { id: 'calendar', label: 'Calendar', path: '/calendar', icon: 'FiCalendar', module: 'calendar', permissions: ['calendar:read:events'] },
  {
    id: 'insights',
    label: 'Intelligence',
    path: '/reports',
    icon: 'FiBarChart2',
    module: 'insights',
    children: [
      { id: 'reports', label: 'Reports', path: '/reports', icon: 'FiFileText', module: 'reports', permissions: ['reporting:read:definitions'] },
      { id: 'analytics', label: 'Analytics', path: '/analytics', icon: 'FiPieChart', module: 'analytics', permissions: ['analytics:read:dashboards'] },
      { id: 'bi', label: 'Business Intelligence', path: '/business-intelligence', icon: 'FiLayers', module: 'bi', permissions: ['bi:read:datasets'] },
    ],
  },
  {
    id: 'communication',
    label: 'Communication',
    path: '/notifications',
    icon: 'FiMessageCircle',
    module: 'communication',
    children: [
      { id: 'notifications', label: 'Notifications', path: '/notifications', icon: 'FiBell', module: 'notifications', permissions: ['notification:read:notifications'], badge: 3 },
      { id: 'messaging', label: 'Messages', path: '/messaging', icon: 'FiMessageSquare', module: 'messaging', permissions: ['messaging:read:channels'] },
      { id: 'announcements', label: 'Announcements', path: '/notifications', icon: 'FiVolume2', module: 'announcements' },
    ],
  },
  { id: 'search', label: 'Search', path: '/search', icon: 'FiSearch', module: 'search', permissions: ['search:read:indexes'] },
  { id: 'ai-assistant', label: 'AI Assistant', path: '/ai-assistant', icon: 'FiCpu', module: 'ai-assistant', permissions: ['ai:read:conversations'] },
  {
    id: 'admin',
    label: 'Administration',
    path: '/administration',
    icon: 'FiSettings',
    module: 'admin',
    roles: ['SUPER_ADMIN', 'ADMIN'],
    children: [
      { id: 'users', label: 'User Management', path: '/users', icon: 'FiUser', module: 'users', permissions: ['personnel:read:profile'] },
      { id: 'roles', label: 'Roles', path: '/administration/roles', icon: 'FiShield', module: 'roles', roles: ['SUPER_ADMIN', 'ADMIN'] },
      { id: 'permissions', label: 'Permissions', path: '/administration/permissions', icon: 'FiKey', module: 'permissions', roles: ['SUPER_ADMIN'] },
      { id: 'audit', label: 'Audit Logs', path: '/audit-logs', icon: 'FiClipboard', module: 'audit', permissions: ['audit:read:logs'] },
      { id: 'settings', label: 'Settings', path: '/settings', icon: 'FiSliders', module: 'settings' },
      { id: 'administration', label: 'System Admin', path: '/administration', icon: 'FiServer', module: 'administration', roles: ['SUPER_ADMIN'] },
    ],
  },
];

export const QUICK_ACTIONS = [
  { label: 'New Leave Request', path: '/leave/new', icon: 'FiCalendar' },
  { label: 'Submit Requisition', path: '/procurement/requisitions/new', icon: 'FiShoppingCart' },
  { label: 'View Reports', path: '/reports', icon: 'FiFileText' },
];
